// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBga_3KhVG8NwBuEWNtOVNTNsTK0xJO7Gk',
    appId: '1:809260903375:web:8ae269e814a27de6fdc0ba',
    messagingSenderId: '809260903375',
    projectId: 'fitbodyapp-82cd4',
    authDomain: 'fitbodyapp-82cd4.firebaseapp.com',
    storageBucket: 'fitbodyapp-82cd4.firebasestorage.app',
    measurementId: 'G-Z7FZ9FJEY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpU1UaTRXCuTOYsUjdskIUUmmaOveO-8k',
    appId: '1:809260903375:android:3d5c2d5878f050c1fdc0ba',
    messagingSenderId: '809260903375',
    projectId: 'fitbodyapp-82cd4',
    storageBucket: 'fitbodyapp-82cd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxLFtvC6x1i9ieRjTwmPwyeLdghBRWuKQ',
    appId: '1:809260903375:ios:cfda87c38b9f3fe7fdc0ba',
    messagingSenderId: '809260903375',
    projectId: 'fitbodyapp-82cd4',
    storageBucket: 'fitbodyapp-82cd4.firebasestorage.app',
    iosBundleId: 'com.example.graduationProjectUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxLFtvC6x1i9ieRjTwmPwyeLdghBRWuKQ',
    appId: '1:809260903375:ios:cfda87c38b9f3fe7fdc0ba',
    messagingSenderId: '809260903375',
    projectId: 'fitbodyapp-82cd4',
    storageBucket: 'fitbodyapp-82cd4.firebasestorage.app',
    iosBundleId: 'com.example.graduationProjectUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBga_3KhVG8NwBuEWNtOVNTNsTK0xJO7Gk',
    appId: '1:809260903375:web:9cbecc90ef22d1b1fdc0ba',
    messagingSenderId: '809260903375',
    projectId: 'fitbodyapp-82cd4',
    authDomain: 'fitbodyapp-82cd4.firebaseapp.com',
    storageBucket: 'fitbodyapp-82cd4.firebasestorage.app',
    measurementId: 'G-2SEQ2T7VXY',
  );
}
